name: 'yelp_transform'
version: '1.0.0'
config-version: 2

profile: 'yelp_transform'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  yelp_transform:
    staging:
      +materialized: view
      +schema: staging
    marts:
      core:
        +materialized: table
        +schema: marts
      business_analytics:
        +materialized: table
        +schema: analytics