yelp_transform:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: localhost # Use the container name
      port: 10001
      schema: yelp_transform
      connect_timeout: 60